### ISSUE TITLE
Delete `venv` directory

### ISSUE THREAD

**Issue by ames0k0** [DePreto/testing_tasks#1]
- [ ] Add `requirements.txt` instead

**Comment by DePreto** [comment]
add requirements.txt, rm venv

**Comment by ames0k0** [comment]
Add dependencies for your tasks (`task{N}.py`) to the `requirements.txt`
-------
#### Steps (for `Python 3.10.7` on GNU Linux)
- [ ] python -m venv `{env_name}`
- [ ] source `{env_name}/bin/activate`
- [ ] pip install `{dependency_name}`
- [ ] pip freeze > `requirements.txt`
